// GENERATED CODE - DO NOT MODIFY BY HAND
 
part of 'json_prefersized_widjet.dart';
 
// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************
 
// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use
 
// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable
 
class preferred_sizeBuilder extends _preferred_sizeBuilder {
  const preferred_sizeBuilder({required super.args});
 
  static const kType = 'preferred_size';
 
  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;
 
  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static preferred_sizeBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) =>
      preferred_sizeBuilder(
        args: map,
      );
 
  @override
  preferred_sizeBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = preferred_sizeBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );
 
    return model;
  }
 
  @override
  PreferredSize buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(
      childBuilder: childBuilder,
      data: data,
    );
 
    return PreferredSize(
      key: key,
      preferredSize: Size.fromHeight(double.parse(model.preferredSize.toString())),
      child: model.child.build(
        childBuilder: childBuilder,
        context: context,
      ),
    );
  }
}
 
class JsonPreferredSize extends JsonWidgetData {
  JsonPreferredSize({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    required this.preferredSize,
    required this.child,
  }) : super(
          jsonWidgetArgs: preferred_sizeBuilderModel.fromDynamic(
            {
              'preferredSize': preferredSize,
              'child': child,
              ...args,
            },
            args: args,
            registry: registry,
          ),
          jsonWidgetBuilder: () => preferred_sizeBuilder(
            args: preferred_sizeBuilderModel.fromDynamic(
              {
                'preferredSize': preferredSize,
                'child': child,
                ...args,
              },
              args: args,
              registry: registry,
            ),
          ),
          jsonWidgetType: preferred_sizeBuilder.kType,
        );
 
  final int preferredSize;
 
  /* AUTOGENERATED FROM [PreferredSize.child]*/
  /// The widget below this widget in the tree.
  ///
  /// {@macro flutter.widgets.ProxyWidget.child}
  final JsonWidgetData child;
}
 
/* AUTOGENERATED FROM [PreferredSize]*/
/// Creates a widget that has a preferred size that the parent can query.
class preferred_sizeBuilderModel extends JsonWidgetBuilderModel {
  const preferred_sizeBuilderModel(
    super.args, {
    required this.preferredSize,
    required this.child,
  });
 
  final int preferredSize;
 
  /* AUTOGENERATED FROM [PreferredSize.child]*/
  /// The widget below this widget in the tree.
  ///
  /// {@macro flutter.widgets.ProxyWidget.child}
  final JsonWidgetData child;
 
  static preferred_sizeBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(
      map,
      args: args,
      registry: registry,
    );
 
    if (result == null) {
      throw Exception(
        '[preferred_sizeBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }
 
    return result;
  }
 
  static preferred_sizeBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    preferred_sizeBuilderModel? result;
 
    if (map != null) {
      if (map is String) {
        map = yaon.parse(
          map,
          normalize: true,
        );
      }
 
      if (map is preferred_sizeBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = preferred_sizeBuilderModel(
          args,
          preferredSize: map['preferredSize'] is int
              ? map['preferredSize']
              : throw Exception(
                  'Invalid value encountered for required parameter: [preferredSize]. Expected an integer.'),
          child: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['child'],
              registry: registry,
            );
 
            if (parsed == null) {
              throw Exception(
                  'Null value encountered for required parameter: [child].');
            }
            return parsed;
          }(),
        );
      }
    }
 
    return result;
  }
 
  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'preferredSize': preferredSize,
      'child': child.toJson(),
      ...args,
    });
  }
}
 
class PreferredSizeSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/convertdifffinger/preferred_size.json';
 
  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'PreferredSize',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'preferredSize': {
        'type': 'integer',
      },
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
  };
}