// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_tab_bar_view.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class TabBarViewBuilder extends _TabBarViewBuilder {
  const TabBarViewBuilder({required super.args});

  static const kType = 'tab_bar_view';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static TabBarViewBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) =>
      TabBarViewBuilder(
        args: map,
      );

  @override
  TabBarViewBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = TabBarViewBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  TabBarView buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(
      childBuilder: childBuilder,
      data: data,
    );

    return TabBarView(
      clipBehavior: model.clipBehavior,
      controller: model.controller,
      dragStartBehavior: model.dragStartBehavior,
      key: key,
      physics: model.physics,
      viewportFraction: model.viewportFraction,
      children: [
        for (var d in model.children)
          d.build(
            childBuilder: childBuilder,
            context: context,
          ),
      ],
    );
  }
}

class JsonTabBarView extends JsonWidgetData {
  JsonTabBarView({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.clipBehavior = Clip.hardEdge,
    this.controller,
    this.dragStartBehavior = DragStartBehavior.start,
    this.physics,
    this.viewportFraction = 1.0,
    required this.children,
  }) : super(
          jsonWidgetArgs: TabBarViewBuilderModel.fromDynamic(
            {
              'clipBehavior': clipBehavior,
              'controller': controller,
              'dragStartBehavior': dragStartBehavior,
              'physics': physics,
              'viewportFraction': viewportFraction,
              'children': children,
              ...args,
            },
            args: args,
            registry: registry,
          ),
          jsonWidgetBuilder: () => TabBarViewBuilder(
            args: TabBarViewBuilderModel.fromDynamic(
              {
                'clipBehavior': clipBehavior,
                'controller': controller,
                'dragStartBehavior': dragStartBehavior,
                'physics': physics,
                'viewportFraction': viewportFraction,
                'children': children,
                ...args,
              },
              args: args,
              registry: registry,
            ),
          ),
          jsonWidgetType: TabBarViewBuilder.kType,
        );

  /* AUTOGENERATED FROM [TabBarView.clipBehavior]*/
  /// {@macro flutter.material.Material.clipBehavior}
  ///
  /// Defaults to [Clip.hardEdge].
  final Clip clipBehavior;

  /* AUTOGENERATED FROM [TabBarView.controller]*/
  /// This widget's selection and animation state.
  ///
  /// If [TabController] is not provided, then the value of [DefaultTabController.of]
  /// will be used.
  final TabController? controller;

  /* AUTOGENERATED FROM [TabBarView.dragStartBehavior]*/
  /// {@macro flutter.widgets.scrollable.dragStartBehavior}
  final DragStartBehavior dragStartBehavior;

  /* AUTOGENERATED FROM [TabBarView.physics]*/
  /// How the page view should respond to user input.
  ///
  /// For example, determines how the page view continues to animate after the
  /// user stops dragging the page view.
  ///
  /// The physics are modified to snap to page boundaries using
  /// [PageScrollPhysics] prior to being used.
  ///
  /// Defaults to matching platform conventions.
  final ScrollPhysics? physics;

  /* AUTOGENERATED FROM [TabBarView.viewportFraction]*/
  /// {@macro flutter.widgets.pageview.viewportFraction}
  final double viewportFraction;

  /* AUTOGENERATED FROM [TabBarView.children]*/
  /// One widget per tab.
  ///
  /// Its length must match the length of the [TabBar.tabs]
  /// list, as well as the [controller]'s [TabController.length].
  final List<JsonWidgetData> children;
}

/* AUTOGENERATED FROM [TabBarView]*/
/// Creates a page view with one child per tab.
///
/// The length of [children] must be the same as the [controller]'s length.
class TabBarViewBuilderModel extends JsonWidgetBuilderModel {
  const TabBarViewBuilderModel(
    super.args, {
    this.clipBehavior = Clip.hardEdge,
    this.controller,
    this.dragStartBehavior = DragStartBehavior.start,
    this.physics,
    this.viewportFraction = 1.0,
    required this.children,
  });

  /* AUTOGENERATED FROM [TabBarView.clipBehavior]*/
  /// {@macro flutter.material.Material.clipBehavior}
  ///
  /// Defaults to [Clip.hardEdge].
  final Clip clipBehavior;

  /* AUTOGENERATED FROM [TabBarView.controller]*/
  /// This widget's selection and animation state.
  ///
  /// If [TabController] is not provided, then the value of [DefaultTabController.of]
  /// will be used.
  final TabController? controller;

  /* AUTOGENERATED FROM [TabBarView.dragStartBehavior]*/
  /// {@macro flutter.widgets.scrollable.dragStartBehavior}
  final DragStartBehavior dragStartBehavior;

  /* AUTOGENERATED FROM [TabBarView.physics]*/
  /// How the page view should respond to user input.
  ///
  /// For example, determines how the page view continues to animate after the
  /// user stops dragging the page view.
  ///
  /// The physics are modified to snap to page boundaries using
  /// [PageScrollPhysics] prior to being used.
  ///
  /// Defaults to matching platform conventions.
  final ScrollPhysics? physics;

  /* AUTOGENERATED FROM [TabBarView.viewportFraction]*/
  /// {@macro flutter.widgets.pageview.viewportFraction}
  final double viewportFraction;

  /* AUTOGENERATED FROM [TabBarView.children]*/
  /// One widget per tab.
  ///
  /// Its length must match the length of the [TabBar.tabs]
  /// list, as well as the [controller]'s [TabController.length].
  final List<JsonWidgetData> children;

  static TabBarViewBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(
      map,
      args: args,
      registry: registry,
    );

    if (result == null) {
      throw Exception(
        '[TabBarViewBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static TabBarViewBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    TabBarViewBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(
          map,
          normalize: true,
        );
      }

      if (map is TabBarViewBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = TabBarViewBuilderModel(
          args,
          clipBehavior: () {
            dynamic parsed = ThemeDecoder.decodeClip(
              map['clipBehavior'],
              validate: false,
            );
            parsed ??= Clip.hardEdge;

            return parsed;
          }(),
          controller: map['controller'],
          dragStartBehavior: () {
            dynamic parsed = ThemeDecoder.decodeDragStartBehavior(
              map['dragStartBehavior'],
              validate: false,
            );
            parsed ??= DragStartBehavior.start;

            return parsed;
          }(),
          physics: () {
            dynamic parsed = ThemeDecoder.decodeScrollPhysics(
              map['physics'],
              validate: false,
            );

            return parsed;
          }(),
          viewportFraction: () {
            dynamic parsed =
                JsonClass.maybeParseDouble(map['viewportFraction']);

            parsed ??= 1.0;

            return parsed;
          }(),
          children: () {
            dynamic parsed = JsonWidgetData.fromDynamicList(
              map['children'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                  'Null value encountered for required parameter: [children].');
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'clipBehavior': Clip.hardEdge == clipBehavior
          ? null
          : ThemeEncoder.encodeClip(
              clipBehavior,
            ),
      'controller': controller,
      'dragStartBehavior': DragStartBehavior.start == dragStartBehavior
          ? null
          : ThemeEncoder.encodeDragStartBehavior(
              dragStartBehavior,
            ),
      'physics': ThemeEncoder.encodeScrollPhysics(
        physics,
      ),
      'viewportFraction': 1.0 == viewportFraction ? null : viewportFraction,
      'children': JsonClass.toJsonList(children),
      ...args,
    });
  }
}

class TabBarViewSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/convertdifffinger/tab_bar_view.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'TabBarView',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'clipBehavior': SchemaHelper.objectSchema(ClipSchema.id),
      'controller': SchemaHelper.anySchema,
      'dragStartBehavior':
          SchemaHelper.objectSchema(DragStartBehaviorSchema.id),
      'physics': SchemaHelper.objectSchema(ScrollPhysicsSchema.id),
      'viewportFraction': SchemaHelper.numberSchema,
      'children': SchemaHelper.arraySchema(JsonWidgetDataSchema.id),
    },
  };
}
