// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_tab.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class TabBuilder extends _TabBuilder {
  const TabBuilder({required super.args});

  static const kType = 'tab';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static TabBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) =>
      TabBuilder(
        args: map,
      );

  @override
  TabBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = TabBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  Tab buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(
      childBuilder: childBuilder,
      data: data,
    );

    return Tab(
      height: model.height,
      icon: model.icon?.build(
        childBuilder: childBuilder,
        context: context,
      ),
      iconMargin: model.iconMargin,
      key: key,
      text: model.text,
      child: model.child?.build(
        childBuilder: childBuilder,
        context: context,
      ),
    );
  }
}

class JsonTab extends JsonWidgetData {
  JsonTab({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.height,
    this.icon,
    this.iconMargin = const EdgeInsets.only(bottom: 10.0),
    this.text,
    this.child,
  }) : super(
          jsonWidgetArgs: TabBuilderModel.fromDynamic(
            {
              'height': height,
              'icon': icon,
              'iconMargin': iconMargin,
              'text': text,
              'child': child,
              ...args,
            },
            args: args,
            registry: registry,
          ),
          jsonWidgetBuilder: () => TabBuilder(
            args: TabBuilderModel.fromDynamic(
              {
                'height': height,
                'icon': icon,
                'iconMargin': iconMargin,
                'text': text,
                'child': child,
                ...args,
              },
              args: args,
              registry: registry,
            ),
          ),
          jsonWidgetType: TabBuilder.kType,
        );

  /* AUTOGENERATED FROM [Tab.height]*/
  /// The height of the [Tab].
  ///
  /// If null, the height will be calculated based on the content of the [Tab]. When `icon` is not
  /// null along with `child` or `text`, the default height is 72.0 pixels. Without an `icon`, the
  /// height is 46.0 pixels.
  final double? height;

  /* AUTOGENERATED FROM [Tab.icon]*/
  /// An icon to display as the tab's label.
  final JsonWidgetData? icon;

  /* AUTOGENERATED FROM [Tab.iconMargin]*/
  /// The margin added around the tab's icon.
  ///
  /// Only useful when used in combination with [icon], and either one of
  /// [text] or [child] is non-null.
  final EdgeInsetsGeometry iconMargin;

  /* AUTOGENERATED FROM [Tab.text]*/
  /// The text to display as the tab's label.
  ///
  /// Must not be used in combination with [child].
  final String? text;

  /* AUTOGENERATED FROM [Tab.child]*/
  /// The widget to be used as the tab's label.
  ///
  /// Usually a [Text] widget, possibly wrapped in a [Semantics] widget.
  ///
  /// Must not be used in combination with [text].
  final JsonWidgetData? child;
}

/* AUTOGENERATED FROM [Tab]*/
/// Creates a Material Design [TabBar] tab.
///
/// At least one of [text], [icon], and [child] must be non-null. The [text]
/// and [child] arguments must not be used at the same time. The
/// [iconMargin] is only useful when [icon] and either one of [text] or
/// [child] is non-null.
class TabBuilderModel extends JsonWidgetBuilderModel {
  const TabBuilderModel(
    super.args, {
    this.height,
    this.icon,
    this.iconMargin = const EdgeInsets.only(bottom: 10.0),
    this.text,
    this.child,
  });

  /* AUTOGENERATED FROM [Tab.height]*/
  /// The height of the [Tab].
  ///
  /// If null, the height will be calculated based on the content of the [Tab]. When `icon` is not
  /// null along with `child` or `text`, the default height is 72.0 pixels. Without an `icon`, the
  /// height is 46.0 pixels.
  final double? height;

  /* AUTOGENERATED FROM [Tab.icon]*/
  /// An icon to display as the tab's label.
  final JsonWidgetData? icon;

  /* AUTOGENERATED FROM [Tab.iconMargin]*/
  /// The margin added around the tab's icon.
  ///
  /// Only useful when used in combination with [icon], and either one of
  /// [text] or [child] is non-null.
  final EdgeInsetsGeometry iconMargin;

  /* AUTOGENERATED FROM [Tab.text]*/
  /// The text to display as the tab's label.
  ///
  /// Must not be used in combination with [child].
  final String? text;

  /* AUTOGENERATED FROM [Tab.child]*/
  /// The widget to be used as the tab's label.
  ///
  /// Usually a [Text] widget, possibly wrapped in a [Semantics] widget.
  ///
  /// Must not be used in combination with [text].
  final JsonWidgetData? child;

  static TabBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(
      map,
      args: args,
      registry: registry,
    );

    if (result == null) {
      throw Exception(
        '[TabBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static TabBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    TabBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(
          map,
          normalize: true,
        );
      }

      if (map is TabBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = TabBuilderModel(
          args,
          height: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['height']);

            return parsed;
          }(),
          icon: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['icon'],
              registry: registry,
            );

            return parsed;
          }(),
          iconMargin: () {
            dynamic parsed = ThemeDecoder.decodeEdgeInsetsGeometry(
              map['iconMargin'],
              validate: false,
            );
            parsed ??= const EdgeInsets.only(bottom: 10.0);

            return parsed;
          }(),
          text: map['text'],
          child: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['child'],
              registry: registry,
            );

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'height': height,
      'icon': icon?.toJson(),
      'iconMargin': const EdgeInsets.only(bottom: 10.0) == iconMargin
          ? null
          : ThemeEncoder.encodeEdgeInsetsGeometry(
              iconMargin,
            ),
      'text': text,
      'child': child?.toJson(),
      ...args,
    });
  }
}

class TabSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/convertdifffinger/tab.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'Tab',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'height': SchemaHelper.numberSchema,
      'icon': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'iconMargin': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'text': SchemaHelper.stringSchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
  };
}
