// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_carousel_slider.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class CarouselSliderBuilder extends _CarouselSliderBuilder {
  const CarouselSliderBuilder({required super.args});

  static const kType = 'carousel_slider';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static CarouselSliderBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) =>
      CarouselSliderBuilder(
        args: map,
      );

  @override
  CarouselSliderBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = CarouselSliderBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  CarouselSlider buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(
      childBuilder: childBuilder,
      data: data,
    );

    return CarouselSlider(
      carouselController: model.carouselController,
      disableGesture: model.disableGesture,
      items: model.items == null
          ? null
          : [
              for (var d in model.items!)
                d.build(
                  childBuilder: childBuilder,
                  context: context,
                ),
            ],
      key: key,
      options: model.options,
    );
  }
}

class JsonCarouselSlider extends JsonWidgetData {
  JsonCarouselSlider({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.carouselController,
    this.disableGesture,
    required this.items,
    required this.options,
  }) : super(
          jsonWidgetArgs: CarouselSliderBuilderModel.fromDynamic(
            {
              'carouselController': carouselController,
              'disableGesture': disableGesture,
              'items': items,
              'options': options,
              ...args,
            },
            args: args,
            registry: registry,
          ),
          jsonWidgetBuilder: () => CarouselSliderBuilder(
            args: CarouselSliderBuilderModel.fromDynamic(
              {
                'carouselController': carouselController,
                'disableGesture': disableGesture,
                'items': items,
                'options': options,
                ...args,
              },
              args: args,
              registry: registry,
            ),
          ),
          jsonWidgetType: CarouselSliderBuilder.kType,
        );

  final CarouselController? carouselController;

  final bool? disableGesture;

  /* AUTOGENERATED FROM [CarouselSlider.items]*/
  /// The widgets to be shown in the carousel of default constructor
  final List<JsonWidgetData>? items;

  /* AUTOGENERATED FROM [CarouselSlider.options]*/
  /// [CarouselOptions] to create a [CarouselState] with
  final CarouselOptions options;
}

class CarouselSliderBuilderModel extends JsonWidgetBuilderModel {
  const CarouselSliderBuilderModel(
    super.args, {
    this.carouselController,
    this.disableGesture,
    required this.items,
    required this.options,
  });

  final CarouselController? carouselController;

  final bool? disableGesture;

  /* AUTOGENERATED FROM [CarouselSlider.items]*/
  /// The widgets to be shown in the carousel of default constructor
  final List<JsonWidgetData>? items;

  /* AUTOGENERATED FROM [CarouselSlider.options]*/
  /// [CarouselOptions] to create a [CarouselState] with
  final CarouselOptions options;

  static CarouselSliderBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(
      map,
      args: args,
      registry: registry,
    );

    if (result == null) {
      throw Exception(
        '[CarouselSliderBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static CarouselSliderBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    CarouselSliderBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(
          map,
          normalize: true,
        );
      }

      if (map is CarouselSliderBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = CarouselSliderBuilderModel(
          args,
          carouselController: map['carouselController'],
          disableGesture: JsonClass.maybeParseBool(
            map['disableGesture'],
          ),
          items: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamicList(
              map['items'],
              registry: registry,
            );

            return parsed;
          }(),
          options: map['options'],
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'carouselController': carouselController,
      'disableGesture': disableGesture,
      'items': JsonClass.maybeToJsonList(items),
      'options': options,
      ...args,
    });
  }
}

class CarouselSliderSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/convertdifffinger/carousel_slider.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'CarouselSlider',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'carouselController': SchemaHelper.anySchema,
      'disableGesture': SchemaHelper.boolSchema,
      'items': SchemaHelper.arraySchema(JsonWidgetDataSchema.id),
      'options': SchemaHelper.anySchema,
    },
  };
}
